version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo4
    ports:
      - "3007:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo4
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL-AUTO: create

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
