version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo4
    ports:
      - "3007:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
